<a href="https://colab.research.google.com/github/anvitank/Study-of-Pandas/blob/main/exp9_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 9
# Title: Study of Pandas Library
## Shreyanshu Behera
## PRN: 25070123149
## ENTC A1

In [ ]:
import pandas as pd

s=pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [1]:
# Create DataFrame
data={"Name":['Soam','Bhavya','Pushpak'],
      "Marks":[98,98,98]}

df=pd.DataFrame(data)
df

NameError: name 'pd' is not defined

In [ ]:
#df.head() is first 5 entries and df.tail() is last 5 entries

In [ ]:
#Structure of DataFrame
df.shape

(3, 2)

In [ ]:
df.ndim

2

In [ ]:
df.size

6

In [ ]:
#Display Column names
df.columns

Index(['Name', 'Marks'], dtype='object')

In [ ]:
#Check data types of each column
df.dtypes

Name     object
Marks     int64
dtype: object

In [ ]:
#Access Individual Column
df['Name']

0       Anvi
1    Srushti
2       Prek
Name: Name, dtype: object

In [ ]:
df['Marks']

0    98
1    98
2    98
Name: Marks, dtype: int64

In [ ]:
#Access specific row
df.loc[1]

Name     Srushti
Marks         98
Name: 1, dtype: object

In [ ]:
#Add a new column
df['Grade']=['A','A','A']
df

      Name  Marks Grade
0     Anvi    100     A
1  Srushti     98     A
2     Prek     98     A

In [ ]:
#Update Data in DataFrame
#Change marks of student
df.loc[0,'Marks']=100
df

      Name  Marks Grade
0     Anvi    100     A
1  Srushti     98     A
2     Prek     98     A

In [ ]:
from numpy import True_
#Delete a column
df.drop('Grade',axis=1,inplace=True)
df

      Name  Marks
0     Anvi    100
1  Srushti     98
2     Prek     98

In [ ]:
#Perform Basic Statistical Analysis
df['Marks'].mean()

np.float64(98.66666666666667)

In [ ]:
df['Marks'].max()

100

In [ ]:
df['Marks'].min()

98

In [ ]:
#Apply Condition
df[df['Marks']>99]

   Name  Marks
0  Anvi    100